"""Write THIRD_PARTY_LICENSES.txt: the licence of every Python package the built app carries.

The EXE and the MSI contain the Python packages this project depends on, and each comes with its
own licence; distributing them means passing those licences on. This takes the runtime dependency
closure of ``snapchat-auto`` from ``uv.lock`` (so it lists exactly what the build installs, nothing
from a developer's environment), reads each installed package's metadata — its licence expression
or classifiers, and the licence files it ships (PEP 639 ``licenses/`` or the usual ``LICENSE*`` /
``COPYING*`` / ``NOTICE*``) — and writes them all into one text file beside LICENSE.

Run from the repository root, in the project's environment (``build_nuitka.cmd`` does):

    python build_tools/collect_licenses.py [output]

It lives outside ``scripts/``, which is bundled into the application. Standard library only. The
files that are not Python packages (sqlcipher3.exe, the emoji font, ccl_bplist.py …) are described by
hand in THIRD_PARTY_NOTICES.md.
"""
import importlib.metadata as md
import os
import sys
import tomllib

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PROJECT = "snapchat-auto"
#: Packages that belong to this repository rather than to a third party.
OWN = {"snapchat-auto", "snapchat-auto-selection"}
_LICENCE_STEMS = ("license", "licence", "copying", "notice", "authors")


def _norm(name):
    return name.lower().replace("_", "-").replace(".", "-")


def runtime_closure(lock_path=os.path.join(ROOT, "uv.lock")):
    """Every package ``snapchat-auto`` needs at run time, by the lock file. Sorted names."""
    with open(lock_path, "rb") as fh:
        lock = tomllib.load(fh)
    deps = {_norm(p["name"]): [_norm(d["name"]) for d in p.get("dependencies", [])]
            for p in lock.get("package", [])}
    seen, todo = set(), [PROJECT]
    while todo:
        name = todo.pop()
        if name in seen:
            continue
        seen.add(name)
        todo += deps.get(name, [])
    return sorted(seen - OWN)


def _licence_files(dist):
    out = []
    for f in dist.files or []:
        parts = [p.lower() for p in f.parts]
        name = parts[-1]
        in_licenses_dir = any(p == "licenses" for p in parts[:-1]) and ".dist-info" in str(f).lower()
        if in_licenses_dir or (".dist-info" in str(f).lower()
                               and name.startswith(_LICENCE_STEMS)):
            out.append(f)
    return out


def describe(name):
    """``(version, licence, homepage, [(file name, text)])`` of one installed package."""
    try:
        dist = md.distribution(name)
    except md.PackageNotFoundError:
        return None
    meta = dist.metadata
    licence = (meta.get("License-Expression") or "").strip()
    if not licence:
        classifiers = [c.split("::")[-1].strip() for c in meta.get_all("Classifier") or []
                       if c.startswith("License ::")]
        licence = "; ".join(classifiers) or (meta.get("License") or "").strip().splitlines()[0:1]
        licence = licence if isinstance(licence, str) else (licence[0] if licence else "")
    homepage = meta.get("Home-page") or ""
    for url in meta.get_all("Project-URL") or []:
        label, _, link = url.partition(",")
        if label.strip().lower() in ("homepage", "source", "repository", "source code"):
            homepage = homepage or link.strip()
    texts = []
    for f in _licence_files(dist):
        try:
            texts.append((str(f).replace("\\", "/").split("/")[-1], f.read_text(encoding="utf-8")))
        except (OSError, UnicodeDecodeError):
            continue
    return dist.version, licence or "(not stated in the package metadata)", homepage, texts


def render(names):
    lines = ["THIRD-PARTY LICENCES — Python packages carried by Snapchat_Auto",
             "",
             "Generated by build_tools/collect_licenses.py from uv.lock and the installed packages'",
             "metadata. The files that are not Python packages are described in",
             "THIRD_PARTY_NOTICES.md. This application itself is MIT-licensed (see LICENSE).",
             ""]
    for name in names:
        info = describe(name)
        lines.append("=" * 78)
        if info is None:
            lines += [f"{name} — not installed in this environment; see its project page", ""]
            continue
        version, licence, homepage, texts = info
        lines += [f"{name} {version}", f"Licence: {licence}"] + ([f"Home: {homepage}"] if homepage else [])
        if not texts:
            lines.append("(the package ships no licence file; the licence above is its own statement)")
        for fname, text in texts:
            lines += ["", f"--- {fname} ---", text.rstrip()]
        lines.append("")
    return "\n".join(lines) + "\n"


def main(argv):
    out = argv[1] if len(argv) > 1 else os.path.join(ROOT, "THIRD_PARTY_LICENSES.txt")
    names = runtime_closure()
    with open(out, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(render(names))
    print(f"{len(names)} package(s) -> {out}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
